In [5]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
df =  pd.read_csv("/content/drive/MyDrive/Đồ Án Phân Tích Dữ Liệu/Source_Code/raw_data.csv", index_col=0)
df = df.fillna('')
df

Make      Model Body color        Interior color  \
0              Fiat       500X       Blue  Other interior color   
1              Ford      Focus      Black  Other interior color   
2           Peugeot        208      White                         
3        Volkswagen      T-Roc      White         Grey interior   
4              Jeep   Wrangler      Black        Black interior   
...             ...        ...        ...                   ...   
1995  Mercedes-Benz      C 180     Silver        Black interior   
1996           Audi         A3      Black        Black interior   
1997          Cupra  Formentor      White        Black interior   
1998  Mercedes-Benz    GLE 400      Black        Black interior   
1999          Dacia    Sandero       Grey        Black interior   

          Interior material              Body      Doors Seats  \
0     Full leather interior     SUV / offroad  4/5 doors     5   
1            Cloth interior     Station Wagon  4/5 doors     5   
2                                   Hatchback  4/5 doors     5   
3            Cloth interior         Cabriolet  4/5 doors     4   
4     Full leather interior     SUV / offroad  4/5 doors     5   
...                     ...               ...        ...   ...   
1995         Cloth interior     Station Wagon  4/5 doors     5   
1996  Part leather interior  Sedans / saloons  4/5 doors     5   
1997         Cloth interior     SUV / offroad  4/5 doors     5   
1998  Full leather interior     SUV / offroad  4/5 doors     5   
1999         Cloth interior         Hatchback  4/5 doors     5   

                              VIN    Fuel  ... Battery capacity  \
0     not published by the seller  Petrol  ...                    
1     not published by the seller  Diesel  ...                    
2     not published by the seller  Petrol  ...                    
3     not published by the seller  Petrol  ...                    
4     not published by the seller  Petrol  ...                    
...                           ...     ...  ...              ...   
1995  not published by the seller  Petrol  ...                    
1996  not published by the seller  Petrol  ...                    
1997  not published by the seller  Petrol  ...                    
1998  not published by the seller  Petrol  ...                    
1999  not published by the seller  Petrol  ...                    

     Range extender Hybrid type AC charging time DC charging time  \
0                                                                   
1                                                                   
2                                                                   
3                                                                   
4                                                                   
...             ...         ...              ...              ...   
1995                                                                
1996                                                                
1997                                                                
1998                                                                
1999                                                                

     Electric range Secondary drive Energy efficiency Full service history  \
0                                                                            
1                                                                            
2                                                                            
3                                                                            
4                                                                            
...             ...             ...               ...                  ...   
1995                                                                         
1996                                                                         
1997                                                                         
199

In [8]:
final_columns = ['Make', 'Model', 'Body color', 'Interior color',
       'Interior material', 'Body', 'Doors', 'Seats', 'Fuel',
       'Transmission', 'Drive type', 'Power', 'Engine capacity',
       'CO2 emissions', 'Emission class', 'Mileage', 'First registration',
       'Battery type', 'AC charging time', 'Battery capacity',
       'Previous owners', 'Warranty until', 'Price']

In [9]:
df = df[final_columns]
df

Make      Model Body color        Interior color  \
0              Fiat       500X       Blue  Other interior color   
1              Ford      Focus      Black  Other interior color   
2           Peugeot        208      White                         
3        Volkswagen      T-Roc      White         Grey interior   
4              Jeep   Wrangler      Black        Black interior   
...             ...        ...        ...                   ...   
1995  Mercedes-Benz      C 180     Silver        Black interior   
1996           Audi         A3      Black        Black interior   
1997          Cupra  Formentor      White        Black interior   
1998  Mercedes-Benz    GLE 400      Black        Black interior   
1999          Dacia    Sandero       Grey        Black interior   

          Interior material              Body      Doors Seats    Fuel  \
0     Full leather interior     SUV / offroad  4/5 doors     5  Petrol   
1            Cloth interior     Station Wagon  4/5 doors     5  Diesel   
2                                   Hatchback  4/5 doors     5  Petrol   
3            Cloth interior         Cabriolet  4/5 doors     4  Petrol   
4     Full leather interior     SUV / offroad  4/5 doors     5  Petrol   
...                     ...               ...        ...   ...     ...   
1995         Cloth interior     Station Wagon  4/5 doors     5  Petrol   
1996  Part leather interior  Sedans / saloons  4/5 doors     5  Petrol   
1997         Cloth interior     SUV / offroad  4/5 doors     5  Petrol   
1998  Full leather interior     SUV / offroad  4/5 doors     5  Petrol   
1999         Cloth interior         Hatchback  4/5 doors     5  Petrol   

     Transmission  ... CO2 emissions     Emission class    Mileage  \
0       Automatic  ...      140 g/km            Euro 6d  14 117 km   
1          Manual  ...       98 g/km  No emission class  85 400 km   
2          Manual  ...       97 g/km             Euro 6  54 030 km   
3       Automatic  ...      130 g/km            Euro 6d   5 000 km   
4       Automatic  ...      276 g/km             Euro 6  77 897 km   
...           ...  ...           ...                ...        ...   
1995    Automatic  ...        0 g/km            Euro 6d  20 359 km   
1996    Automatic  ...      144 g/km       Euro 6d-TEMP  57 642 km   
1997    Automatic  ...      175 g/km            Euro 6d   8 365 km   
1998    Automatic  ...      204 g/km             Euro 6  81 500 km   
1999    Automatic  ...      129 g/km            Euro 6d      43 km   

     First registration Battery type AC charging time Battery capacity  \
0                2/2022                                                  
1                6/2020                                                  
2                6/2020                                                  
3                8/2023                                                  
4                1/2019                                                  
...                 ...          ...              ...              ...   
1995            11/2022                                                  
1996             7/2019                                                  
1997            11/2022                                                  
1998             4/2018                                                  
1999             9/2023                                                  

     Previous owners Warranty until  Price  
0                2.0                 28899  
1                                    18799  
2                1.0        12/2024  18599  
3                1.0                 42649  
4                                    59999  
...              ...            ...    ...  
1995             1.0                 39149  
1996                                 29899  
1997                                 40799  
1998             1.0                 47399  
1999             2.0                 18849  

[2000 rows x 23 columns]

In [10]:
df = df.drop_duplicates().reset_index(drop=True)
df

Make      Model Body color        Interior color  \
0              Fiat       500X       Blue  Other interior color   
1              Ford      Focus      Black  Other interior color   
2           Peugeot        208      White                         
3        Volkswagen      T-Roc      White         Grey interior   
4              Jeep   Wrangler      Black        Black interior   
...             ...        ...        ...                   ...   
1970  Mercedes-Benz      C 180     Silver        Black interior   
1971           Audi         A3      Black        Black interior   
1972          Cupra  Formentor      White        Black interior   
1973  Mercedes-Benz    GLE 400      Black        Black interior   
1974          Dacia    Sandero       Grey        Black interior   

          Interior material              Body      Doors Seats    Fuel  \
0     Full leather interior     SUV / offroad  4/5 doors     5  Petrol   
1            Cloth interior     Station Wagon  4/5 doors     5  Diesel   
2                                   Hatchback  4/5 doors     5  Petrol   
3            Cloth interior         Cabriolet  4/5 doors     4  Petrol   
4     Full leather interior     SUV / offroad  4/5 doors     5  Petrol   
...                     ...               ...        ...   ...     ...   
1970         Cloth interior     Station Wagon  4/5 doors     5  Petrol   
1971  Part leather interior  Sedans / saloons  4/5 doors     5  Petrol   
1972         Cloth interior     SUV / offroad  4/5 doors     5  Petrol   
1973  Full leather interior     SUV / offroad  4/5 doors     5  Petrol   
1974         Cloth interior         Hatchback  4/5 doors     5  Petrol   

     Transmission  ... CO2 emissions     Emission class    Mileage  \
0       Automatic  ...      140 g/km            Euro 6d  14 117 km   
1          Manual  ...       98 g/km  No emission class  85 400 km   
2          Manual  ...       97 g/km             Euro 6  54 030 km   
3       Automatic  ...      130 g/km            Euro 6d   5 000 km   
4       Automatic  ...      276 g/km             Euro 6  77 897 km   
...           ...  ...           ...                ...        ...   
1970    Automatic  ...        0 g/km            Euro 6d  20 359 km   
1971    Automatic  ...      144 g/km       Euro 6d-TEMP  57 642 km   
1972    Automatic  ...      175 g/km            Euro 6d   8 365 km   
1973    Automatic  ...      204 g/km             Euro 6  81 500 km   
1974    Automatic  ...      129 g/km            Euro 6d      43 km   

     First registration Battery type AC charging time Battery capacity  \
0                2/2022                                                  
1                6/2020                                                  
2                6/2020                                                  
3                8/2023                                                  
4                1/2019                                                  
...                 ...          ...              ...              ...   
1970            11/2022                                                  
1971             7/2019                                                  
1972            11/2022                                                  
1973             4/2018                                                  
1974             9/2023                                                  

     Previous owners Warranty until  Price  
0                2.0                 28899  
1                                    18799  
2                1.0        12/2024  18599  
3                1.0                 42649  
4                                    59999  
...              ...            ...    ...  
1970             1.0                 39149  
1971                                 29899  
1972                                 40799  
1973             1.0                 47399  
1974             2.0                 18849  

[1975 rows x 23 columns]

# Xử lý Body color

In [11]:
df['Body color'].unique()

array(['Blue', 'Black', 'White', 'Grey', 'Red', 'Silver', 'Green', '',
       'Yellow', 'Brown', 'Orange', 'Beige', 'Gold', 'Purple'],
      dtype=object)

In [12]:
df_copy = df.copy()
for i in range(len(df)):
    if df['Body color'][i] == '':
        df['Body color'][i] = df_copy[(df_copy['Make'] == df['Make'][i])
                                 | (df_copy['Model'] == df['Model'][i])]['Body color'].mode()[0]
        if df['Body color'][i] == '':
            df['Body color'][i] = np.nan

In [13]:
df['Body color'].unique()

array(['Blue', 'Black', 'White', 'Grey', 'Red', 'Silver', 'Green',
       'Yellow', 'Brown', 'Orange', nan, 'Beige', 'Gold', 'Purple'],
      dtype=object)

# Xử lý Interior color

In [14]:
df['Interior color'].unique()

array(['Other interior color', '', 'Grey interior', 'Black interior',
       'Brown interior', 'Beige interior'], dtype=object)

In [15]:
df_copy = df.copy()
for i in range(len(df)):
    if df['Interior color'][i] == '':
        df['Interior color'][i] = df_copy[((df_copy['Make'] == df['Make'][i])
                                      | (df_copy['Model'] == df['Model'][i]))]['Interior color'].mode()[0]
        if df['Interior color'][i] == '':
            df['Interior color'][i] = np.nan

In [16]:
df['Interior color'].unique()

array(['Other interior color', nan, 'Grey interior', 'Black interior',
       'Brown interior', 'Beige interior'], dtype=object)

# Xử lý Interior material

In [17]:
df['Interior material'].unique()

array(['Full leather interior', 'Cloth interior', '',
       'Alcantara interior', 'Other interior material',
       'Part leather interior', 'Velour interior'], dtype=object)

In [18]:
df_copy = df.copy()
for i in range(len(df)):
    if df['Interior material'][i] == '':
        df['Interior material'][i] = df_copy[(df_copy['Make'] == df['Make'][i])
                                        | (df_copy['Model'] == df['Model'][i])]['Interior material'].mode()[0]
        if df['Interior material'][i] == '':
            df['Interior material'][i] = np.nan

In [19]:
df['Interior material'].unique()

array(['Full leather interior', 'Cloth interior', nan,
       'Alcantara interior', 'Other interior material',
       'Part leather interior', 'Velour interior'], dtype=object)

# Xử lý Doors

In [20]:
df_copy = df.copy()
for i in range(len(df)):
    if df['Doors'][i] == '':
        df['Doors'][i] = df_copy[(df_copy['Make'] == df['Make'][i])
                            & (df_copy['Model'] == df['Model'][i])]['Doors'].mode()[0]
        if df['Doors'][i] == '':
            df['Doors'][i] = np.nan

In [21]:
df['Doors'].unique()

array(['4/5 doors', '2/3 doors', nan], dtype=object)

# Xử lý Seats

In [22]:
df_copy = df.copy()
for i in range(len(df)):
    if df['Seats'][i] == '':
        df['Seats'][i] = df_copy[(df_copy['Make'] == df['Make'][i])
                            & (df_copy['Model'] == df['Model'][i])]['Seats'].mode()[0]
        if df['Seats'][i] == '':
            df['Seats'][i] = np.nan

In [23]:
df['Seats'].unique()

array(['5', '4', '7', '6', nan, '3', '2', '8+', '9+', '1'], dtype=object)

# Xử lý Power

In [24]:
df['Power'].unique()[:5]

array(['111 kW', '88 kW', '74 kW', '110 kW', '209 kW'], dtype=object)

In [25]:
df['Power'] = [int(p.split()[0]) for p in df['Power']]

In [26]:
df['Power'].unique()[:5]

array([111,  88,  74, 110, 209])

# Xử lý Engine capacity

In [27]:
df['Engine capacity'].unique()[:5]

array(['1\xa0332 ccm', '1\xa0498 ccm', '1\xa0199 ccm', '3\xa0604 ccm',
       '1\xa0395 ccm'], dtype=object)

In [28]:
df['Engine capacity'].replace('', '0', inplace=True)
df['Engine capacity'] = [int((''.join(x.split('\xa0'))).split(' ')[0]) for x in df['Engine capacity']]

df_copy = df.copy()
for i in range(len(df)):
    if df['Engine capacity'][i] == 0:
        df['Engine capacity'][i] = int(df_copy[(df_copy['Make'] == df['Make'][i])
                            | (df_copy['Model'] == df['Model'][i])]['Engine capacity'].mean())
        if df['Engine capacity'][i] == 0:
            df['Engine capacity'][i] = np.nan

In [29]:
df['Engine capacity'].unique()[:5]

array([1332., 1498., 1199., 3604., 1395.])

# Xử lý CO2 emissions

In [30]:
df['CO2 emissions'].unique()[:5]

array(['140 g/km', '98 g/km', '97 g/km', '130 g/km', '276 g/km'],
      dtype=object)

In [31]:
df['CO2 emissions'] = [int(p.split()[0]) for p in df['CO2 emissions']]

In [32]:
df['CO2 emissions'].unique()[:5]

array([140,  98,  97, 130, 276])

# Xử lý Emission class

In [33]:
df['Emission class'].unique()

array(['Euro 6d', 'No emission class', 'Euro 6', 'Euro 6d-TEMP', 'Euro 5',
       '', 'Euro 6c'], dtype=object)

In [34]:
df_copy = df.copy()
for i in range(len(df)):
    if df['Emission class'][i] == '':
        df['Emission class'][i] = df_copy[(df_copy['Fuel'] == df['Fuel'][i])
                            & (df_copy['CO2 emissions'] == df['CO2 emissions'][i])]['Emission class'].mode()[0]
        if df['Emission class'][i] == '':
            df['Emission class'][i] = np.nan

In [35]:
df['Emission class'].unique()

array(['Euro 6d', 'No emission class', 'Euro 6', 'Euro 6d-TEMP', 'Euro 5',
       'Euro 6c', nan], dtype=object)

# Xử lý Mileage

In [36]:
df['Mileage'].unique()[:5]

array(['14\xa0117 km', '85\xa0400 km', '54\xa0030 km', '5\xa0000 km',
       '77\xa0897 km'], dtype=object)

In [37]:
df['Mileage'] = [int(''.join(m.split('\xa0')).split()[0]) for m in df['Mileage']]

In [38]:
df['Mileage'].unique()[:5]

array([14117, 85400, 54030,  5000, 77897])

# Xử lý First registration

In [39]:
df['First registration'].unique()[:5]

array(['2/2022', '6/2020', '8/2023', '1/2019', '5/2022'], dtype=object)

In [40]:
df['First registration'] = [int(f.split('/')[1]) for f in df['First registration']]

In [41]:
df['First registration'].unique()[:5]

array([2022, 2020, 2023, 2019, 2018])

# Xử lý Battery type

In [42]:
df['Battery type'].unique()

array(['', 'Lithium-ion (Li-ion)', 'Nickel-metal hydride (NiMH)',
       'Lithium polymer (Li-pol)'], dtype=object)

In [43]:
df_copy = df.copy()
for i in range(len(df)):
    if df['Battery type'][i] == '':
        df['Battery type'][i] = df_copy[(df_copy['Fuel'] == 'Electric')
                                        | (df_copy['Fuel'] == 'Hybrid')]['Battery type'].mode()[0]
        if df['Battery type'][i] == '':
            if df['Fuel'][i] not in ['Electric', 'Hybrid']:
                df['Battery type'][i] = 'No battery type class'
            else: df['Battery type'][i] = np.nan


In [44]:
df['Battery type'].unique()

array(['No battery type class', nan, 'Lithium-ion (Li-ion)',
       'Nickel-metal hydride (NiMH)', 'Lithium polymer (Li-pol)'],
      dtype=object)

# Xử lý AC charging time

In [45]:
df['AC charging time'].unique()

array(['', '3 h', '4 h', '10 h', '8 h', '1 h', '12 h', '7 h', '6 h',
       '13 h', '2 h', '5 h', '9 h'], dtype=object)

In [46]:
df['AC charging time'].replace('', '0', inplace=True)
df['AC charging time'] = [int(t.split()[0]) for t in df['AC charging time']]

df_copy = df.copy()
for i in range(len(df)):
    if df['AC charging time'][i] == 0:
        df['AC charging time'][i] = float(df_copy[(df_copy['Battery type'] == df['Battery type'][i])
                                        & (df_copy['Power'] == df['Power'][i])]['AC charging time'].mean())
        if df['AC charging time'][i] == 0:
            if df['Fuel'][i] not in ['Electric', 'Hybrid']:
                df['AC charging time'][i] = 0
            else: df['AC charging time'][i] = np.nan


In [47]:
df['AC charging time'].unique()

array([ 0.        ,         nan,  3.33333333,  3.        ,  1.05263158,
        4.        ,  1.5       , 10.        ,  1.        ,  8.        ,
       12.        ,  7.        ,  6.        ,  5.55555556, 13.        ,
        2.        ,  5.        ,  9.        ])

# Xử lý Battery capacity

In [48]:
df['Battery capacity'].unique()

array(['', '82 kWh', '12 kWh', '50 kWh', '24 kWh', '42 kWh', '1 kWh',
       '13 kWh', '36 kWh', '95 kWh', '14 kWh', '9 kWh', '40 kWh',
       '18 kWh', '59 kWh', '10 kWh', '71 kWh', '76 kWh', '28 kWh',
       '32 kWh', '85 kWh', '2 kWh', '23 kWh', '17 kWh', '45 Ah', '66 kWh',
       '90 kWh', '11 kWh', '64 kWh', '22 kWh', '6 Ah', '31 kWh', '58 kWh',
       '15 kWh', '111 kWh', '84 kWh', '60 kWh', '70 kWh', '99 kWh',
       '78 kWh', '34 kWh', '25 kWh', '3 Ah', '62 kWh', '67 kWh', '93 kWh',
       '77 kWh', '19 kWh', '55 kWh', '81 kWh'], dtype=object)

In [49]:
df['Battery capacity'].replace('', '0', inplace=True)
df['Battery capacity'] = [int(t.split()[0]) for t in df['Battery capacity']]

df_copy = df.copy()
for i in range(len(df)):
    if df['Battery capacity'][i] == 0:
        df['Battery capacity'][i] = float(df_copy[(df_copy['Battery type'] == df['Battery type'][i])
                                        & (df_copy['Power'] == df['Power'][i])]['Battery capacity'].mean())
        if df['Battery capacity'][i] == 0:
            if df['Fuel'][i] not in ['Electric', 'Hybrid']:
                df['Battery capacity'][i] = 0
            else: df['Battery capacity'][i] = np.nan


In [50]:
df['Battery capacity'].unique()

array([0.00000000e+00,            nan, 8.20000000e+01, 1.02000000e+01,
       1.20000000e+01, 1.40845070e-02, 5.00000000e+01, 2.40000000e+01,
       4.20000000e+01, 1.00000000e+00, 1.30000000e+01, 3.60000000e+01,
       9.50000000e+01, 1.40000000e+01, 9.00000000e+00, 4.00000000e+01,
       1.80000000e+01, 4.81904762e+01, 5.90000000e+01, 1.00000000e+01,
       7.10000000e+01, 7.60000000e+01, 2.80000000e+01, 3.20000000e+01,
       8.50000000e+01, 2.00000000e+00, 2.30000000e+01, 8.40000000e+00,
       1.70000000e+01, 4.50000000e+01, 6.60000000e+01, 9.00000000e+01,
       1.10000000e+01, 6.40000000e+01, 2.19000000e+01, 2.20000000e+01,
       6.00000000e+00, 3.10000000e+01, 5.80000000e+01, 1.50000000e+01,
       1.11000000e+02, 8.40000000e+01, 6.00000000e+01, 7.00000000e+01,
       9.66666667e+00, 9.90000000e+01, 7.80000000e+01, 3.40000000e+01,
       2.50000000e+01, 7.00000000e+00, 3.00000000e+00, 6.20000000e+01,
       6.70000000e+01, 9.30000000e+01, 7.70000000e+01, 1.90000000e+01,
      

# Xử lý Previous owners

In [51]:
df['Previous owners'].unique()

array([2.0, '', 1.0, 4.0, 3.0], dtype=object)

In [52]:
for i in range(len(df)):
    if df['Previous owners'][i]:
        df['Previous owners'][i] = str(int(df['Previous owners'][i]))
    else:
        df['Previous owners'][i] = 'Unknown'

In [53]:
df['Previous owners'].unique()

array(['2', 'Unknown', '1', '4', '3'], dtype=object)

# Xử lý Warranty until

In [54]:
df['Warranty until'].unique()

array(['', '12/2024', '12/2025', '12/2028', '12/2026', '04/2024',
       '05/2024', '06/2024', '07/2026', '08/2024', '12/2030', '03/2024'],
      dtype=object)

In [55]:
make, value = [], []
for i in range(len(df)):
    if df['First registration'][i] and len(df['Warranty until'][i]):
        make.append(df['Make'][i])
        value.append(int(df['Warranty until'][i].split('/')[1]) - df['First registration'][i])

In [56]:
d = {}
for name in pd.Series(make).unique():
    l = []
    for i in range(len(make)):
        if make[i] == name:
            l.append(value[i])
    d[name] = l

In [57]:
for i in range(len(df)):
    if df['Warranty until'][i]:
        df['Warranty until'][i] = int(df['Warranty until'][i].split('/')[1]) - df['First registration'][i]
    else:
        if df['Make'][i] in d:
            df['Warranty until'][i] = int(np.mean(d[df['Make'][i]]))
        else: df['Warranty until'][i] = np.nan

In [58]:
df['Warranty until'] = df['Warranty until'].astype('float')
df['Warranty until'].unique()

array([ 3.,  5.,  4., nan,  6.,  2.,  7.,  1.,  8., 12.,  9.])

# Xử lý Price

In [59]:
df['Price'] = df['Price'].astype('float')

# Loại bỏ Nan

In [60]:
df.isnull().sum()

Make                    0
Model                   0
Body color              7
Interior color        107
Interior material      90
Body                    0
Doors                   6
Seats                  27
Fuel                    0
Transmission            0
Drive type              0
Power                   0
Engine capacity         5
CO2 emissions           0
Emission class          4
Mileage                 0
First registration      0
Battery type          264
AC charging time      299
Battery capacity      233
Previous owners         0
Warranty until         68
Price                   0
dtype: int64

In [61]:
df = df.dropna().reset_index(drop=True)
df

Make      Model Body color        Interior color  \
0              Fiat       500X       Blue  Other interior color   
1              Ford      Focus      Black  Other interior color   
2        Volkswagen      T-Roc      White         Grey interior   
3              Audi         S5       Grey        Black interior   
4               BMW        118      White        Black interior   
...             ...        ...        ...                   ...   
1498  Mercedes-Benz      C 180     Silver        Black interior   
1499           Audi         A3      Black        Black interior   
1500          Cupra  Formentor      White        Black interior   
1501  Mercedes-Benz    GLE 400      Black        Black interior   
1502          Dacia    Sandero       Grey        Black interior   

          Interior material              Body      Doors Seats    Fuel  \
0     Full leather interior     SUV / offroad  4/5 doors     5  Petrol   
1            Cloth interior     Station Wagon  4/5 doors     5  Diesel   
2            Cloth interior         Cabriolet  4/5 doors     4  Petrol   
3        Alcantara interior             Coupe  4/5 doors     5  Diesel   
4     Full leather interior         Hatchback  4/5 doors     5  Petrol   
...                     ...               ...        ...   ...     ...   
1498         Cloth interior     Station Wagon  4/5 doors     5  Petrol   
1499  Part leather interior  Sedans / saloons  4/5 doors     5  Petrol   
1500         Cloth interior     SUV / offroad  4/5 doors     5  Petrol   
1501  Full leather interior     SUV / offroad  4/5 doors     5  Petrol   
1502         Cloth interior         Hatchback  4/5 doors     5  Petrol   

     Transmission  ... CO2 emissions     Emission class  Mileage  \
0       Automatic  ...           140            Euro 6d    14117   
1          Manual  ...            98  No emission class    85400   
2       Automatic  ...           130            Euro 6d     5000   
3       Automatic  ...           161       Euro 6d-TEMP    43800   
4       Automatic  ...           111             Euro 6    18104   
...           ...  ...           ...                ...      ...   
1498    Automatic  ...             0            Euro 6d    20359   
1499    Automatic  ...           144       Euro 6d-TEMP    57642   
1500    Automatic  ...           175            Euro 6d     8365   
1501    Automatic  ...           204             Euro 6    81500   
1502    Automatic  ...           129            Euro 6d       43   

      First registration           Battery type  AC charging time  \
0                   2022  No battery type class               0.0   
1                   2020  No battery type class               0.0   
2                   2023  No battery type class               0.0   
3                   2020  No battery type class               0.0   
4                   2019  No battery type class               0.0   
...                  ...                    ...               ...   
1498                2022  No battery type class               0.0   
1499                2019  No battery type class               0.0   
1500                2022  No battery type class               0.0   
1501                2018  No battery type class               0.0   
1502                2023  No battery type class               0.0   

      Battery capacity Previous owners  Warranty until    Price  
0             0.000000               2             3.0  28899.0  
1             0.000000         Unknown             5.0  18799.0  
2             0.000000               1             3.0  42649.0  
3             0.000000               2             4.0  56049.0  
4             0.000000               1             6.0  29649.0  
...                ...             ...             ...      ...  
1498          0.000000               1             4.0  39149.0  
1499          0.014085         Unknown             4.0  29899.0  
1500          0.000000         Unknown             3.0  40799.0  
1501          0

# Loại bỏ Outlier

In [62]:
Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)

# Tính IQR
IQR = Q3 - Q1

# Xác định giá trị ngoại lệ
lower_extreme = Q1 - 1.5 * IQR
upper_extreme = Q3 + 1.5 * IQR

df = df[(df['Price'] >= lower_extreme) & (df['Price'] <= upper_extreme)]

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1409 entries, 0 to 1502
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Make                1409 non-null   object 
 1   Model               1409 non-null   object 
 2   Body color          1409 non-null   object 
 3   Interior color      1409 non-null   object 
 4   Interior material   1409 non-null   object 
 5   Body                1409 non-null   object 
 6   Doors               1409 non-null   object 
 7   Seats               1409 non-null   object 
 8   Fuel                1409 non-null   object 
 9   Transmission        1409 non-null   object 
 10  Drive type          1409 non-null   object 
 11  Power               1409 non-null   int64  
 12  Engine capacity     1409 non-null   float64
 13  CO2 emissions       1409 non-null   int64  
 14  Emission class      1409 non-null   object 
 15  Mileage             1409 non-null   int64  
 16  First 

# Lưu lại file dữ liệu

In [64]:
df.reset_index(drop=True).to_csv('final_data.csv', index=False)